### ISSUE TITLE
Update contents in README to be about PayMeLah

### ISSUE THREAD

**Issue by waynezsy** [AY2223S1-CS2103T-W13-3/tp#12]

**Comment by lyuting47** [comment]
Remember to change the CI status link as well

**Comment by waynezsy** [comment]
That should have been already done in #9.

**Comment by lyuting47** [comment]
> That should have been already done in #9.

That was for README.md, index.md (the landing page of the project page) has to be updated accordingly as well

**Comment by waynezsy** [comment]
@lyuting47 Should probably start a new issue to update index.md then. There's other stuff inside about AB3 too.
