### ISSUE TITLE
[PE-D][Tester B] Adding a debt of $0 is allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-3/tp#228]
A debt of $0 is allowed in the adding debt command. But this does not make sense usability-wise. Perhaps, should not allow users to add $0 debts

![image.png](https://raw.githubusercontent.com/Eugenetanwl3881/ped/main/files/2773716c-2cfc-4cf1-8170-9c49866c9904.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Eugenetanwl3881/ped#6

**Comment by waynezsy** [comment]
Not all debts need to have a monetary value.
By enabling $0 debts, users can make use of the debt feature for other forms of creative debt tracking, such as `adddebt d/charger m/0` if their friend owes the user a charger (which does not require an explicit monetary value attached).
