### ISSUE TITLE
[PE-D][Tester E] No editing of debts supported

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-3/tp#244]
As this is an app to manage debts, editing debts is an important feature that should be supported.

Cases such as: not fully paying debts

This app requires the user to delete a debt and re-create it with different details. An edit feature would make it a lot simpler.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nitant-p/ped#7

**Comment by waynezsy** [comment]
Feature was decided to be lower priority than other features.
Can be replicated by add and delete.

**Comment by waynezsy** [comment]
Not fully paying debts - target user is students, not a common scenario to have big debts that require multiple installments. This contributed to the lowered priority of an edit debt feature.
