### ISSUE TITLE
[PE-D][Tester A] Clear Debts on someone with no debts

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-3/tp#247]
Hi. I tested the `cleardebts` on a person with no debts and it passes through. Should it work that way. Consider throwing an error since that person does not owe the user.

Steps to take:

1. Input `cleardebts 2` and press enter.
2. Input `cleardebts 2` again and press enter.
3. It shows that person `2` has her debts cleared even though it was already cleared.

![image.png](https://raw.githubusercontent.com/ChongCheeKaiClarence/ped/main/files/8ecbffdb-2344-4b34-a4ca-ca6b8c2ae3a6.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ChongCheeKaiClarence/ped#4

**Comment by WR3nd3** [comment]
In this instance, clear command will return a message that the specified person's debts have been cleared. An error was not determined to be high priority since a user is likely to care more that the person's debts are now cleared than the fact that they were already clear.
